AssetManagement/Controllers/AssetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AssetManagement.Data;
using AssetManagement.Models;
using Microsoft.EntityFrameworkCore.Query;
using AssetManagement.ViewModels;
using static AssetManagement.Models.Extension;
using AssetManagement.Models.Abstraction.Enums;

namespace AssetManagement.Controllers
{
    public class AssetsController : Controller
    {
        private readonly DataContext _context;

        public AssetsController(DataContext context)
        {
            _context = context;
        }

        private async Task<List<AssetViewModel>> GetAssetsAsync()
        {
            var data = await _context.Asset
               .Include(x => x.Extension)
                   .ThenInclude(x => x.Employee)
                       .ThenInclude(x => x.Department)
               .Include(x => x.Telephone)
                   .ThenInclude(x => x.SubCategory)
                       .ThenInclude(x => x.Category)
               .Select(x => new AssetViewModel
               {
                   TelephoneId = x.TelephoneSerialNo,
                   ExtensionId = x.ExtensionNumber,
                   Employee = x.Extension.Employee.Name,
                   BadgeNo = x.Extension.Employee.BadgeNo,
                   SerialNo = x.Telephone.SerialNo,
                   MAC = x.Telephone.MAC,
                   Model = x.Telephone.SubCategory.Name,
                   Brand = x.Telephone.SubCategory.Category.Name,
                   Extension = x.Extension.Number,
                   Department = x.Extension.Employee.Department.Name
               })
               .AsNoTracking()
               .ToListAsync();
            return data;
        }
        public async Task<IActionResult> Index() => View(await GetAssetsAsync());

        public async Task<IActionResult> Details(string serialNo, int? number)
        {
            if (serialNo == null || number == null)
            {
                return NotFound();
            }

            var asset = await _context.Asset
                .Include(a => a.Extension)
                    .ThenInclude(a => a.Employee)
                        .ThenInclude(a => a.Department)
                .Include(a => a.Telephone)
                    .ThenInclude(a => a.SubCategory)
                        .ThenInclude(a => a.Category)
                .FirstOrDefaultAsync(m => m.TelephoneSerialNo == serialNo && m.ExtensionNumber == number);
            if (asset == null)
            {
                return NotFound();
            }

            return View(asset);
        }

        public IActionResult Create()
        {
            var extension = _context.Extension.Where(x => x.Usage == ExtensionUsage.EndUser);
            var telephone = _context.Telephone.Where(x => x.Status == Status.Stock);
            ViewData["Number"] = new SelectList(extension, "Number", "Number");
            ViewData["SerialNo"] = new SelectList(telephone, "SerialNo", "SerialNo");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TelephoneSerialNo,ExtensionNumber")] Asset asset)
        {
            if (ModelState.IsValid)
            {
                // 1. Remove telephone from stock, update telephone status to used;
                var telephone = _context.Telephone.FirstOrDefault(x => x.SerialNo == asset.TelephoneSerialNo);
                telephone.Status = Status.Used;
                _context.Update(telephone);
                await _context.SaveChangesAsync();
                // 2. Add asset
                _context.Add(asset);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Number"] = new SelectList(_context.Extension, "Id", "Number", asset.ExtensionNumber);
            ViewData["SerialNo"] = new SelectList(_context.Telephone, "Id", "SerialNo", asset.TelephoneSerialNo);
            return View(asset);
        }

        public async Task<IActionResult> Edit(string serialNo, int? number)
        {
            if (serialNo == null || number == null)
            {
                return NotFound();
            }

            var asset = await _context.Asset
                .Where(x => x.TelephoneSerialNo == serialNo && x.ExtensionNumber == number)
                .FirstOrDefaultAsync();
            if (asset == null)
            {
                return NotFound();
            }
            ViewData["Number"] = new SelectList(_context.Extension, "Id", "Number", asset.ExtensionNumber);
            ViewData["SerialNo"] = new SelectList(_context.Telephone, "Id", "SerialNo", asset.TelephoneSerialNo);
            return View(asset);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string serialNo, int number, [Bind("TelephoneSerialNo,ExtensionNumber")] Asset asset)
        {
            if (serialNo != asset.TelephoneSerialNo || number != asset.ExtensionNumber)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // problem here - handle extension usage. 
                    _context.Update(asset);
                    await _context.SaveChangesAsync();
                    var extension = UpdateExtensionStatus(asset);
                    _context.Update(extension);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AssetExists(asset.TelephoneSerialNo, asset.ExtensionNumber))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Number"] = new SelectList(_context.Extension, "Id", "Number", asset.ExtensionNumber);
            ViewData["SerialNo"] = new SelectList(_context.Telephone, "Id", "SerialNo", asset.TelephoneSerialNo);
            return View(asset);
        }

        public async Task<IActionResult> Delete(string serialNo, int? number)
        {
            if (serialNo == null || number == null)
            {
                return NotFound();
            }

            var asset = await _context.Asset
                .Include(a => a.Extension)
                .Include(a => a.Telephone)
                .FirstOrDefaultAsync(m => m.TelephoneSerialNo == serialNo && m.ExtensionNumber == number);
            if (asset == null)
            {
                return NotFound();
            }

            return View(asset);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string telephoneSerialNo, int extensionNumber)
        {
            if (telephoneSerialNo == null || extensionNumber == 0)
            {
                return NotFound();
            }
            // 1. Change extension status to Available
            // TODO: i need to think about it
            var extension = UpdateExtensionOnDelete(extensionNumber);
            _context.Update(extension);
            await _context.SaveChangesAsync();
            // 2. Add telephone back to stock.
            var telephone = AddTelephoneToStock(telephoneSerialNo);
            _context.Update(telephone);
            await _context.SaveChangesAsync();
            // 3. Remove asset
            var asset = _context.Asset
                .Where(x => x.TelephoneSerialNo == telephoneSerialNo && x.ExtensionNumber == extensionNumber)
                .FirstOrDefault();
            _context.Asset.Remove(asset);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AssetExists(string serialNo, int number)
        {
            return _context.Asset.Any(e => e.TelephoneSerialNo == serialNo && e.ExtensionNumber == number);
        }

        private Extension UpdateExtensionStatus(Asset asset)
        {
            var extension = _context.Extension.Find(asset.ExtensionNumber);
            extension.Usage = ExtensionUsage.EndUser;
            return extension;
        }

        private Extension UpdateExtensionOnDelete(int number)
        {
            var extension = _context.Extension.Find(number);
            extension.Usage = ExtensionUsage.Available;
            return extension;
        }

        private Telephone AddTelephoneToStock(string serialNo)
        {
            var telephone = _context.Telephone.Find(serialNo);
            telephone.Status = Status.Stock;
            return telephone;
        }
    }
}

AssetManagement/Controllers/PagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AssetManagement.Data;
using AssetManagement.Models;


//TODO:  Handle Pager assignment with employee - update - delete

namespace AssetManagement.Controllers
{
    public class PagerController : Controller
    {
        private readonly DataContext _context;

        public PagerController(DataContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var dataContext = _context.Pager.Include(p => p.Employee);
            return View(await dataContext.ToListAsync());
        }

        public async Task<IActionResult> Details(string serialNo)
        {
            if (serialNo == null)
            {
                return NotFound();
            }

            var pager = await _context.Pager
                .Include(p => p.Employee)
                .FirstOrDefaultAsync(m => m.SerialNo == serialNo);
            if (pager == null)
            {
                return NotFound();
            }

            return View(pager);
        }

        public IActionResult Create()
        {
            ViewData["BadgeNo"] = new SelectList(_context.Employee, "BadgeNo", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Number,Capcode,BadgeNo,Comment,Cust,RateCode,SerialNo,Status,MailCode,Facility")] Pager pager)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pager);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BadgeNo"] = new SelectList(_context.Employee, "BadgeNo", "Name", pager.EmployeeBadgeNo);
            return View(pager);
        }

        public async Task<IActionResult> Edit(string serialNo)
        {
            if (serialNo == null)
            {
                return NotFound();
            }

            var pager = await _context.Pager.FindAsync(serialNo);
            if (pager == null)
            {
                return NotFound();
            }
            ViewData["BadgeNo"] = new SelectList(_context.Employee, "BadgeNo", "Name", pager.EmployeeBadgeNo);
            return View(pager);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string serialNo, [Bind("Number,Capcode,BadgeNo,Comment,Cust,RateCode,SerialNo,Status,MailCode,Facility")] Pager pager)
        {
            if (serialNo != pager.SerialNo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pager);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PagerExists(pager.SerialNo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BadgeNo"] = new SelectList(_context.Employee, "BadgeNo", "Name", pager.EmployeeBadgeNo);
            return View(pager);
        }

        public async Task<IActionResult> Delete(string serialNo)
        {
            if (serialNo == null)
            {
                return NotFound();
            }

            var pager = await _context.Pager
                .Include(p => p.Employee)
                .FirstOrDefaultAsync(m => m.SerialNo == serialNo);
            if (pager == null)
            {
                return NotFound();
            }

            return View(pager);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string serialNo)
        {
            var pager = await _context.Pager.FindAsync(serialNo);
            _context.Pager.Remove(pager);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PagerExists(string serialNo)
        {
            return _context.Pager.Any(e => e.SerialNo == serialNo);
        }
    }
}

AssetManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AssetManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/DataTables/datatables.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AssetManagement</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Telephone" asp-action="Index">Telephone</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Extension" asp-action="Index">Extension</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assets" asp-action="Index">Assets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pager" asp-action="Index">Pager</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Brands</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SubCategory" asp-action="Index">Model</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AssetManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/Chartjs/dist/Chart.js"></script>
    <script src="~/lib/Chartjs/dist/Chart.bundle.js"></script>
    <script src="~/lib/DataTables/datatables.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>